development: &default
  adapter:  postgis
  encoding: unicode
  database: mbcr_development
  host:     localhost
  port:     5432
  pool:     5

test:
  <<: *default
  database: mbcr_test

production:
  url: <%= ENV['DATABASE_URL'] %>
